### ISSUE TITLE
Replace Indicators Name (Labels) with Shorter Names 

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/kcsf-data-visualizer#10]
[CS Index Visualizer Indicator Labels_final.docx](https://github.com/opendatakosovo/kcsf-data-visualizer/files/799836/CS.Index.Visualizer.Indicator.Labels_final.docx)

**Comment by egzontina** [comment]
@dafinaolluri  In order to estimate this,  I need to know where exactly we should make those replacements and the list of those Shorter Names?

**Comment by georgeslabreche** [comment]
@dafinaolluri we can't test this because we don't know what is meant by label. Please provide clarity.
