### ISSUE TITLE
In the main indicator rename the disaggregated ones in the screenshot 

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/kcsf-data-visualizer#15]
Rename these questions in: 
In which year was your organization established?
Does your organization have a public beneficiary status?

- [ ] Year of establishment 
- [ ] Public Beneficiary Status

<img width="558" alt="screen shot 2017-02-24 at 5 05 18 pm" src="https://cloud.githubusercontent.com/assets/24916965/23311063/0c492f4c-fab5-11e6-9b30-b0a3277afe91.png">

**Comment by egzontina** [comment]
@dafinaolluri please provide translations for three languages!

**Comment by dafinaolluri** [comment]
@egzontina Please see below the relevant translations: 

 Year of establishment- Viti i themelimit -Godina osnivanj
Public Beneficiary Status- Statusi per Perfitim Publik -statusa javnog korisnika
