### ISSUE TITLE
Implement tutorial slideshow.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/kcsf-data-visualizer#17]
- [x] We are going to use jQuery tourbus:
https://ryanfunduk.com/jquery-tourbus/

- [ ]  Will have to be in three languages.

- [x]  There will be a "tutorial" or "help" button/link on the navigation header that will trigger a 5 modal tutorial:

- [ ] The 5 modals are:
1. Select a topic you wish to analyze.
2. Specify the indicator you are interested in.
3. Visualize the data with one of four available charts: a piechart, horizontal or vertical barcharts, or a pointchart.
4. Dig deeper in how the data is distributed by applying disaggregation.
5. Download the report, datasets, and questionnaire.

**Comment by georgeslabreche** [comment]
@dafinaolluri please get translation for these instructions.

**Comment by dafinaolluri** [comment]
@georgeslabreche If you can make some time for a meeting with Diamant and me to discuss about the text that we are going to use in the tutorial.

**Comment by dafinaolluri** [comment]
@georgeslabreche @diamanthaxhimusa I talked with KCSF they agreed on the text, the translations for Albanian and Serbian will be provided tomorrow.

**Comment by dafinaolluri** [comment]
@diamanthaxhimusa @georgeslabreche KCSF guys said for the informal language to use the **Next** and **Back** as a formal language.

**Comment by dafinaolluri** [comment]
@diamanthaxhimusa Please see below the translations:

**ENG**
Select a topic you wish to analyze. 
Specify the indicator you are interested in. 
Visualize the data with one of four available charts: a piechart, horizontal or vertical barcharts, or a pointchart. 
Dig deeper in how the data is distributed by applying disaggregation. 
Download the report, datasets, and questionnaire.

**SHQ**
Zgjedhni temën të cilën dëshironi t’a analizoni 
Përcaktoni indikatorin që ju intereson
Prezantoni të dhënat në njërën nga katër format e grafikoneve në dispozicion
Thellohuni në të dhënat, duke i krahasuar indikatorët në mes vete
Shkarkoni raportin, bazën e të dhënave si dhe pyetësorin

**SRB**
Izaberite temu koju želite da analizirate.
Navedite indikator za koji ste zainteresovani. 
Vizualizirajte podatke sa jednim od četiri dostupna grafikona. 
Istražite više kako se podaci distribuiraju primenom disagregacije indikatora.
Preuzmite izveštaj, podatake i upitnik.

**Comment by dafinaolluri** [comment]
@diamanthaxhimusa For mobile version, use this reference https://app.decoders.amnesty.org/project/decode-the-difference/tutorial. I will talk to you again in your free time before starting to work on Tuesday.
