### ISSUE TITLE
5 Indicators from UNDP Public Pulse make Aggregated Data 

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/kcsf-data-visualizer#27]
**Description**
As a user I want to be able to see the whole percentage of the population, not to see firstly disaggregated by women and men. 

**Tema**  "Vullnetarizmi dhe aktivizmi"** 

- [ ] "Angazhimi qytetar ne OSHC",
- [ ] "Pervoja e qytetareve me OSHC",

**Tema** "Perceptimet mbi shoqerine civile"**

- [ ]  "Shoqeria civile ne Kosove si monitorues i besushem i zhvillimeve Demokratike ne Kosove"
- [ ]  "Besimi nderpersonal", 
- [ ] "Perceptimi mbi korrupsionin ne OSHC"

![screen shot 2017-03-15 at 2 26 13 pm](https://cloud.githubusercontent.com/assets/24916965/23950504/81aad13e-098b-11e7-9c86-006acc4ec59e.png)

Example: 
![screen shot 2017-03-15 at 2 12 20 pm](https://cloud.githubusercontent.com/assets/24916965/23950368/0a94c6fe-098b-11e7-9f2f-74730750c53c.png)

![screen shot 2017-03-15 at 2 25 04 pm](https://cloud.githubusercontent.com/assets/24916965/23950421/3829a152-098b-11e7-9a78-49441e36392c.png)

![screen shot 2017-03-15 at 2 28 48 pm](https://cloud.githubusercontent.com/assets/24916965/23950600/cbb380fa-098b-11e7-8dac-39e83462cd6b.png)

![screen shot 2017-03-15 at 2 34 57 pm](https://cloud.githubusercontent.com/assets/24916965/23950832/9a969344-098c-11e7-8c9c-3cdfdd674bf7.png)

**Comment by dafinaolluri** [comment]
@georgeslabreche Can you please review this task when you have time?

**Comment by georgeslabreche** [comment]
@dafinaolluri OK, I need proper time to test this thoroughly but will do!
