### ISSUE TITLE
Replace indicator text from their current form (as a question) to a shorter format.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/kcsf-data-visualizer#4]
[CS Index Visualizer Indicator Labels_final.docx](https://github.com/opendatakosovo/kcsf-data-visualizer/files/799849/CS.Index.Visualizer.Indicator.Labels_final.docx)

**Comment by egzontina** [comment]
@dafinaolluri Is the format provided? If yes, where can I find that list, if no, I can't estimate this!
