### ISSUE TITLE
Q77 disaggregate by q7 (333.66%)

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/kcsf-data-visualizer#6]
This is happening only in the first topic: Funding 

@egzontina Please see the link below for further explanations: 

![screen shot 2017-02-24 at 5 25 29 pm](https://cloud.githubusercontent.com/assets/24916965/23311403/52cd5604-fab6-11e6-8fa3-994313608e94.png)

**Comment by egzontina** [comment]
I need more information.

**Comment by dafinaolluri** [comment]
@egzontina Already attached the picture above. I have edited in Georges comment!!
