### ISSUE TITLE
Add download reports and download dataset (to be provided)

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/kcsf-data-visualizer#7]

**Comment by egzontina** [comment]
@dafinaolluri  Is it provided? If yes, where?  What kind of report should be downloaded, I need more information..

**Comment by georgeslabreche** [comment]
@egzontina can you make the pdf file names more descriptive? For example, instead of "report-sr-2016.pdf" have it as "KCSF - Kosovoski indeks civilnog društva - Oktobar 2016.pdf"
